package cord.roles;

import java.util.HashMap;

import cord.common.AllProperties;
import cord.common.RoleNames;
import cord.common.BaseNodeLabels;
import cord.model.Perm;

public class Roles {
  private HashMap<String, Perm> p;
  public Roles(){
    this.p = new HashMap<String, Perm>();

    addPerm(BaseNodeLabels.Budget, AllProperties.about, RoleNames.AdministratorRole, Perm.NO);

    Object[][] matrix = {                                                 /*  Admin,   PM G,    PM P,    RD G,    RD P,    FOD,     FA G,    FA P,    CTRL,    CM,      FUN,     MAR,     STAF,    LEAD,    INT,     LIA,     MEN,     RCC,     TRA,     CON        */
      {BaseNodeLabels.Budget, AllProperties.universalTemplateFile,            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.records,                          Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.status,                           Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {BaseNodeLabels.Budget, AllProperties.about,                            Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW, Perm.RW },
      {},
    };

    Integer baseNodePropertyCombos = 15;
    Integer roles = 19;

    for (Integer i = 0; i < baseNodePropertyCombos; i++){
      BaseNodeLabels baseNode = null;
      AllProperties property = null;
      for (Integer j = 0; j < roles; j++){
        switch (j){
          case (0):  baseNode = (BaseNodeLabels) matrix[i][j]; break;
          case (1):  property = (AllProperties) matrix[i][j]; break;
          case (2):  this.addPerm(baseNode, property, RoleNames.AdministratorRole, (Perm) matrix[i][j]); break;
          case (3):  this.addPerm(baseNode, property, RoleNames.ProjectManagerGlobalRole, (Perm) matrix[i][j]); break;
          case (4):  this.addPerm(baseNode, property, RoleNames.ProjectManagerOnProjectRole, (Perm) matrix[i][j]); break;
          case (5):  this.addPerm(baseNode, property, RoleNames.RegionalDirectorGlobalRole, (Perm) matrix[i][j]); break;
          case (6):  this.addPerm(baseNode, property, RoleNames.RegionalDirectorOnProjectRole, (Perm) matrix[i][j]); break;
          case (7):  this.addPerm(baseNode, property, RoleNames.FieldOperationsDirectorRole, (Perm) matrix[i][j]); break;
          case (8):  this.addPerm(baseNode, property, RoleNames.FinancialAnalystGlobalRole, (Perm) matrix[i][j]); break;
          case (9):  this.addPerm(baseNode, property, RoleNames.FinancialAnalystOnProjectRole, (Perm) matrix[i][j]); break;
          case (10): this.addPerm(baseNode, property, RoleNames.ControllerRole, (Perm) matrix[i][j]); break;
          case (11): this.addPerm(baseNode, property, RoleNames.ConsultantManagerRole, (Perm) matrix[i][j]); break;
          case (12): this.addPerm(baseNode, property, RoleNames.FundraisingRole, (Perm) matrix[i][j]); break;
          case (13): this.addPerm(baseNode, property, RoleNames.MarketingRole, (Perm) matrix[i][j]); break;
          case (14): this.addPerm(baseNode, property, RoleNames.StaffMemberRole, (Perm) matrix[i][j]); break;
          case (15): this.addPerm(baseNode, property, RoleNames.LeadershipRole, (Perm) matrix[i][j]); break;
          case (16): this.addPerm(baseNode, property, RoleNames.InternRole, (Perm) matrix[i][j]); break;
          case (17): this.addPerm(baseNode, property, RoleNames.LiasonRole, (Perm) matrix[i][j]); break;
          case (18): this.addPerm(baseNode, property, RoleNames.MentorRole, (Perm) matrix[i][j]); break;
          case (19): this.addPerm(baseNode, property, RoleNames.RegionalCommunicationCoordinatorRole, (Perm) matrix[i][j]); break;
          case (20): this.addPerm(baseNode, property, RoleNames.TranslatorRole, (Perm) matrix[i][j]); break;
          case (21): this.addPerm(baseNode, property, RoleNames.ConsultantRole, (Perm) matrix[i][j]); break;
        }
      }
    }
  }

  private void addPerm(
    BaseNodeLabels baseNode, 
    AllProperties property, 
    RoleNames role, 
    Perm perm
  ){
    this.p.put(baseNode.name()+":"+property.name()+":"+role.name(), perm);
  }
  
}
